### ISSUE TITLE
Orderstatus

### ISSUE THREAD

**Issue by wassengen** [vippsas/vipps-woocommerce#12]
On orders that are quick-check purchases, the order comes in with the status "on hold", which means that the customer does not receive a receipt for completed purchases before we actually have packed and sent the order. There will also be a problem on follow-up emails on these customers. They automatically receive mail to complete the purchase since these are not registered as a completed purchase customer.

Is there a solution to this problem?

**Comment by iverok** [comment]
Yes, several. You can set up Woo to change the way emails are sent, but since it is practical to keep the 'on-hold' status for problematic orders, you can now instead set the "Processing" status as the end-state in the setup page for the Vipps gateway.

You need to be aware if you do this that even though the payment status is "Processing", the payment will only have been reserved, not captured. You must then ensure that the payment is captured (right before) you ship.  This is why "On-hold" is the default state - normally, "Processing"-orders will be captured and ready to ship.

You will find this setting at

  /wp-admin/admin.php?page=wc-settings&tab=checkout&section=vipps

Right after the key set up. You can there choose "On hold" or "Processing", if you need more end-states you will have to use the provided filters.

Products that are both virtual and downloadable will be captured automatically.

**Comment by cloveras** [comment]
Hi, @wassengen 

Just checking if we (read: @iverok) can offer more help, or if we should close this issue? 

Christian, Vipps

**Comment by iverok** [comment]
I believe this issue as stated should be considered solved by using the "Processing" as the end-state of the operation (which is now an option) and remembering to capture all non-autocapturable transactions before sending the packages, in particular with respect to emails.

If this is chosen, the "on-hold" state will only mean that there is a payment problem (e.g., capture failed).   It is only important to remember that capture *could* fail before sending

If there are still issues with the order statuses I'll be happy to try to help.

**Comment by cloveras** [comment]
Closing 💥
