### ISSUE TITLE
Test environment

### ISSUE THREAD

**Issue by rafal-sokolowski** [vippsas/vipps-woocommerce#19]
Why does FAQ section in the README.md file state that Vipps doesn't offer a test environment while, in fact, there is one and it works like a charm? I've just tested it to make sure I'm not delusional.

https://github.com/vippsas/vipps-developers/blob/master/vipps-getting-started.md

**Comment by iverok** [comment]
Yes, the wording is perhaps a bit off. The meaning is that there is no test environment in the Woocommerce plugin itself  of the kind you could turn on and off in the settings like there is in some gateways.

The reason this isn't implemented is that you need both the separate test-mode Vipps app from Testflight and a separate test Vipps account to be able to run in test mode;  for most "end user" merchants this would be difficult and confusing to handle.

For developers test mode *is* supported as you note.  You just need to set the VIPPS_TEST_MODE constant and use the appropriate keys - and of course, to complete payments, to have the test app installed on some device.

**Comment by rafal-sokolowski** [comment]
Well, I get your point but still, I think this is misleading and it should be corrected.

In addition to it, I'm aware of the fact that for some how the test mode in Vipps works may be difficult to understand but having a test mode switch in the settings would be a really nice to have option. It can always be described as for developers only. Currently, it's a little bit painful when in order to test the gateway I have to log in to the server and enable the constant.

**Comment by iverok** [comment]
I can fix the wording for next release to be sure. As for a switch in the backend; I'd rather not add it as it's a lot better for support to have fewer settings, in particular one that would for almost all users simply break their site and which they won't be able to use. (It's a lot easier to answer "why does test mode work" as opposed to "why doesn't test mode work").

Since Vipps support refunds, it's pretty easy to test in the live environment for regular users. I do both of course.

However, I get not wanting to have to edit the config file (and remembering to edit the config file). Maybe a "Vipps Developer and Test Mode" additional plugin could be easier to work with? I guess the test mode keys could then be overriden in the dev/test plugin, so that both live and dev keys could be used concurrently, with testmode as a toggle in the aux.

**Comment by rafal-sokolowski** [comment]
I completely agree with KISS principle. Furthermore, keeping that in mind, I think creating additional Vipps developer plugin would overcomplicate the game.

In order not to confuse users, the test mode options could be separated in a different tab or section. I don't want to push but the idea is not new. See, for instance, how Klarna Checkout for WooCommerce handles this.

**Comment by forsvunnet** [comment]
Just to add my 2 cents. Every other payment plugin I've used for WooCommerce has a checkbox for "Test mode". I nearly tore my hair out in frustration before I discovered the `VIPPS_TEST_MODE` constant.
It would be really great to see this as a checkbox setting in a future version of the plugin.

**Comment by iverok** [comment]
Yes, but other plugins don't require installing a separate test app on a dedicated mobile device.  Turning on test mode in the plugin will not in itself allow you to test the plugin, you need a whole different environment for it.

**Comment by forsvunnet** [comment]
Other payment providers usually require a separate test account on a different url from the live environment. Eg. Klarna uses a playground prefix for their test environment.

Some examples:
![image](https://user-images.githubusercontent.com/799281/63768828-86fda280-c8d1-11e9-9ab5-ca0a534e04d6.png)
![image](https://user-images.githubusercontent.com/799281/63768898-b0b6c980-c8d1-11e9-961a-7861c991e247.png)
![image](https://user-images.githubusercontent.com/799281/63769009-f96e8280-c8d1-11e9-9de0-a4a264f315d8.png)

**Comment by iverok** [comment]
Yes, of course. But the separate app, not from the app store,  on a separate device is a different thing altogether, and this is the main reason this feature isn't advertised.  

You would of course need three additional separate keys if you wanted to switch quickly between live and test modes. So four extra settings, a separate account and a separate device with an app installed from testflight.

**Comment by forsvunnet** [comment]
How about something like this:
![image](https://user-images.githubusercontent.com/799281/63771689-eb236500-c8d7-11e9-89c2-129dcf8b5327.png)

**Comment by iverok** [comment]
Thats' a good design with the tabs, but it isn't really supported by the Woocommerce Settings API. (*) 

If I were to add this, I would probably add a single setting for "Enable developer mode", and then create a separate settings page for that, including test keys and so forth, that would only show when enabled. 

I do switch between test and live mode myself, so I see the usefulness,  but as I said, this is a developer-only feature due to the requirements of a separate app and device. A generally-available 'test mode' switch should allow a general user to actually enter test mode without too much trouble, and this doesn't do that.

*) Though you can do it by either rewriting the DOM using javascript, or overriding admin_options and bypassing the API entirely.

**Comment by forsvunnet** [comment]
The WooCommerce settings api is very limited and I would encourage making custom DOM and javascript. We do the same thing for the bring-fraktguiden plugin.

I understand what you're saying about a test mode being generally available, but that's also true for the other payment methods I showed examples of. The test mode i not generally available. To get access to the test mode you usually have to apply for a test account and be verified before you can start using it. I work for an agency and for us testing is critical. If we can't test a payment method we generally won't sign clients up for that provider. I know the same is true for other agencies as well so I would recommend making testing as easy as possible.

Separating the test and live credentials has an added benefit when migrating databases from a live environment to a test-site. You then only have to tick the checkbox instead of filling in the test-credentials every time you do a database update on the test site.

**Comment by iverok** [comment]
The point again is the requirement for a separate app on a separate device, which is a bit more involved than getting to the test modes of the other payment methods I've used; and certainly more complicated than adding a constant to the wp-config file.  

You do have a very good point about migrating the databases, and in general, being able to turn test mode on and off without editing the keys, not least because I have to do this a lot myself, and it does get a bit old.

I'll add that as the test-mode Vipps app is in fact the developer version, the live and test environment don't always function 100% alike. At least when adding or modding features, it is therefore neccessary to test against the live environment as well as the test environment. For which it would also be very nice to have a toggle of course.

I'll look into adding a test/dev environment switch then.

**Comment by iverok** [comment]
The 'master' branch on github now has a "dev mode" switch which switches on the dev mode features, which currently is just the test mode. I've tried turning this on and off on my testsites; and this works, switching between live and test accounts. It saves quite a bit of time actually, and non-developer users will hopefully not press both the dev button, the test-button and then get confused.

The dev mode settings are kept on the same page for simplicitys sake - obviously, as the number of options grow there will have to be some tabs or some other kind of organisation there.

Release of this will be delayed a bit due to other concerns and some more testing. Probably the week after next.

**Comment by iverok** [comment]
"Dev mode" and "Test mode" should be live shortly in version 1.2.2.

**Comment by iverok** [comment]
Closing this now as it seems to work ok.
