### ISSUE TITLE
Set order status to completed with virtual/downloadable products

### ISSUE THREAD

**Issue by kentf** [vippsas/vipps-woocommerce#2]
Hi,

Would it be possible to set an order to `completed` when there is a `SALE` and all products are of the type virtual and downloadable? So files will be instantly available to the user on purchase. The current behavior sets the order to `processing`.

I've tried hacking the code, and it just takes too much time to understand both WooCommerce and Vipps processes, and how they are implemented in the plugin.

This is how far I've tested. I don't know if it breaks anything. I guess the server needs to tell Vipps to transfer funds on the `completed` step, and it's here I fall short.

```diff
diff --git a/htdocs/wp-content/plugins/woo-vipps/WC_Gateway_Vipps.class.php b/htdocs/wp-content/plugins/woo-vipps/WC_Gateway_Vipps.class.php
index 0a5500ea..8389d8f1 100644
--- a/htdocs/wp-content/plugins/woo-vipps/WC_Gateway_Vipps.class.php
+++ b/htdocs/wp-content/plugins/woo-vipps/WC_Gateway_Vipps.class.php
@@ -643,7 +643,14 @@ class WC_Gateway_Vipps extends WC_Payment_Gateway {
                 $newstatus = 'on-hold';
                 break;
             case 'SALE':
-                $newstatus = 'processing';
+                if ($order->needs_processing())
+                {
+                    $newstatus = 'processing';
+                }
+                else
+                {
+                    $newstatus = 'completed';
+                }
                 break;
             case 'CANCEL':
             case 'VOID':
@@ -667,7 +674,7 @@ class WC_Gateway_Vipps extends WC_Payment_Gateway {
         }

         // We have a completed order, but the callback haven't given us the payment details yet - so handle it.
-        if (($newstatus == 'on-hold' || $newstatus=='processing') && $order->get_meta('_vipps_express_checkout') && !$order->get_billing_email()) {
+        if (($newstatus == 'on-hold' || $newstatus=='processing' || $newstatus=='completed') && $order->get_meta('_vipps_express_checkout') && !$order->get_billing_email()) {
             $this->log(__("Express checkout - no callback yet, so getting payment details from Vipps", 'woo-vipps'));


@@ -696,6 +703,10 @@ class WC_Gateway_Vipps extends WC_Payment_Gateway {
                     wc_reduce_stock_levels($order->get_id());
                     $order->update_status('processing', __( 'Payment captured at Vipps', 'woo-vipps' ));
                     break;
+                case 'completed':
+                    $order->update_status('completed', __( 'Payment captured at Vipps (completed)', 'woo-vipps' ));
+                    break;
                 case 'cancelled':
                     $order->update_status('cancelled', __('Order failed or rejected at Vipps', 'woo-vipps'));
                     break;
```

Thanks

**Comment by cloveras** [comment]
Hi @kentf 

Thanks for very good input!

We have discussed this functionality, and while it did not make the initial release (we wanted to make the plugin available as quickly as possible), it is still in the backlog for an upcoming release.

Christian , Vipps

**Comment by iverok** [comment]
In addition to the time issue, this feature (auto-capture) was elided
because it simplifies things to have just one "Path" for all orders, which
helps with stability and debugging.

It is possible; although you wouldn't dispatch on SALE - That status was
added in that branch just for completeness. The system will always RESERVE
the orders the way orders are created now so they will need to be CAPTUREd.
That is, you will need only to examine the Woo status and do the actions on
the transitions there - you don't have to examine the statuses at Vipps.

You should be able to implement this outside of the plugin by creating an
action on a suitable hook after the order has been put "on-hold" (like
'woocommerce_order_status_on-hold').  In that, instantiate the
WC_Gateway_Vipps class, check that the order is virtual and downloadble and
that the payment method is Vipps. Then call the "capture_payment" method,
checking for exceptions. If no exceptions are thrown, you can change the
order status to "completed".  See the method maybe_capture_payment in
WC_Gateway_Vipps for the basic flow - this is called when you set the order
to 'completed' manually.

In the future we  also plan to add actions and filters to the plugin to
make this type of customization easier.

Regards,
Iver Odin Kvello
iver@wp-hosting.no


2018-08-16 12:57 GMT+02:00 Kent <notifications@github.com>:

**Comment by kentf** [comment]
Thanks @iverok 

I took the liberty to modify the plugin itself, adding a hook in `Vipps.class.php` on the `woocommerce_order_status_on-hold` action. It checks if the order needs processing, and if not, sets the order to completed. With my testing, it sets the order to completed if it contains only virtual and downloadable products.

I know the proper way is to generate a pull request for patches, but this is so small so I'll just publish the diff here.

```diff
diff --git a/woo-vipps/Vipps.class.php b/woo-vipps/Vipps.class.php
index 21ec1ff8..25326548 100644
--- a/woo-vipps/Vipps.class.php
+++ b/woo-vipps/Vipps.class.php
@@ -306,7 +306,7 @@ class Vipps {
         add_action('wp_ajax_nopriv_do_express_checkout', array($this, 'ajax_do_express_checkout'));
         add_action('wp_ajax_do_express_checkout', array($this, 'ajax_do_express_checkout'));

-
+        add_action('woocommerce_order_status_on-hold', array($this, 'complete_virtual_orders'));
     }

     public function save_order($postid,$post,$update) {
@@ -915,4 +915,26 @@ class Vipps {
         return $wp_post;
     }

+    public function complete_virtual_orders($orderid)
+    {
+        // $this->log("complete_virtual_orders: orderid $orderid");
+
+        $order = new WC_Order($orderid);
+       $pm = $order->get_payment_method();
+
+        // Check payment method
+        if ($pm != 'vipps')
+            return;
+
+        // Needs processing?
+        if ($order->needs_processing())
+            return;
+
+        // $this->log("no processing needed: order $orderid");
+
+       // Try to complete order. At this point this order only
+       // contains virtual and downloadable products
+       $order->set_status('completed');
+       $order->save();
+    }
 }
```

**Comment by iverok** [comment]
Thank you for your patch! 

The only issue with it is that you cannot assume that a capture will be successful (because of all this happening over the net and so forth). Both temporary and permanent errors are possible. Therefore there is error checking in the transition from 'on-hold' to 'completed' that will revert the status to 'on-hold' if the capture fails.

Normally your code should work fine though; but to make it safer,  you should do the capture, protectedy by a try/except, and only then set the status to 'completed' if it succeeds.

I can add the code as sketched to the main branch, but the behaviour will be off by default and toggled on in user settings - hope that will work out for you.

In the mean time, your code, especially as amended above, is correct.

**Comment by kentf** [comment]
I'd like to have this functionality as a part of the main branch, even though it's off by default.

I think the default should be "on" by default. As far as I know, that's how the official WooCommerce PayPal plugin handles products that are downloadable and virtual.

**Comment by iverok** [comment]
It will be part of the main branch.

"On" by default: Well, maybe. I've just been very wary of doing 'capture' automatically because of the possible consequences of errors in this codepath.  When the code is stable and trusted it makes sense to make it 'on' by default.

**Comment by iverok** [comment]
I'm closing this issue as autocapture is now possible in 1.0.5.
