### ISSUE TITLE
Vipps doesn't show up if Woo is network enabled

### ISSUE THREAD

**Issue by thoaud** [vippsas/vipps-woocommerce#3]
Vipps doesn't show up in the payment setting if WooCommerce is network activated in a multisite install.

**Comment by iverok** [comment]
Thank you for your report.  I will replicate and add a fix for this.

**Comment by iverok** [comment]
Bug is found and fixed and will be a part of next release.

The problem was this code
 ` apply_filters( 'active_plugins', get_option( 'active_plugins' ));`

Which I got from the "WooCommerce Plugin Developer Handbook". It does not take into account network installs of WooCommerce. This code is changed in the master branch and tested on both network and single sites.
