### ISSUE TITLE
Improvement: Add filter to payment_return_url(), so we can add custom tracking parameters.

### ISSUE THREAD

**Issue by Razko90** [vippsas/vipps-woocommerce#50]
It would be nice to add parameters to the return url.

`
public function payment_return_url() {
        return apply_filters( 'vipps_payment_return_url', $this->make_return_url('vipps-betaling') );
}
`

So we can add e.g. utm_nooverride so the analytics shows the correct soruce / medium :)

**Comment by iverok** [comment]
Sure thing, except for consistency the filter should use the woo_vipps prefix:

`return apply_filters('woo_vipps_payment_return_url', $this->make_return_url('vipps-betaling'));`

Adding it for next version.

One thing though: The returnurl will normally wait for the result from Vipps before redirecting to the normal "Thankyou" page. On failure, it will stay on this page. On page load, success/failure may still be undefined.   It is possible to use a custom error return page to which the browser would redirect on order failure/cancellation.

If the result is undefined on page return, a javascript will periodically check the order status before the final redirect happens. It is possible to add hooks here too if you have a recent WordPress.

This part of the process is due for a bit of review because apparently some JS code that ought to trigger on the "thankyou" page does not in fact trigger on the "thankyou" page in some situations. I have not been able to replicate this myself.

**Comment by iverok** [comment]
Filter added.
