### ISSUE TITLE
'processing' when amount is reserved

### ISSUE THREAD

**Issue by thoaud** [vippsas/vipps-woocommerce#7]
Vipps orders, when placed, gets status 'on-hold'.

> = Why are orders put on-hold and not reserved or completed? =
When the order is on-hold the payment is reserved, but not yet transferred to the merchant. The money must be 'captured' before they are acutally transfered to the merchang. You are normally only allowed to do this at the same time as the order is shipped. You can 'capture' the money explitly on the order screen; but the money will be captured automatically when the order is set to "Processing" or "Complete".

This disrupts the usual process of order handling since any other payment gateway uses 'on-hold' as a status of which the order needs to be looked at manually. E.g awaiting payment, fraud risk is too high etc. Processing is the regular status for every order that is OK, and is ready to be shipped. And an order that has the order amount reserved in the payment gateway should get 'processing', and not as an order awaiting payment i.e 'on-hold'.

Most external WMS etc also imports all orders with status 'processing', and set the order as 'completed' when shipped. This means that disrupting the regular status flow could cause issues with stores using WMS, external order management etc.

When a order is captured and everything is OK the statuses should be like this:
1. Vipps reserved ok -> Processing
2. Order completed ->  Vipps Capture

This flow is used by Stripe, Klarna, Collector and PayPal. So I would say it's safe to say it's the regular flow.

I also think a simple filter to control what status the order should get when vipps has reserved the amount is a good idea. So that if you need another status, or even a custom one, that is possible.

**Comment by iverok** [comment]
When the order is reserved at Vipps, the payment is not yet complete. The money is reserved, but it has still not been transferred to the merchant, and in fact this transfer - the capture - can theoretically fail.  

Other plugins notwithstanding, I had to work with the documentation when implementing this, and as noted here: https://docs.woocommerce.com/document/managing-orders/:

>   Processing – Payment received (paid) and stock has been reduced; order is awaiting fulfillment.
>   On-Hold – Awaiting payment – stock is reduced, but you need to confirm payment.

and not least here: https://docs.woocommerce.com/document/advanced-payment-gateway-features/ directly discussing this feature (as an 'advanced feature'):

> When payment is authorized for an order, the order status will be set to “on hold”. You can edit the order by going to WooCommerce > Orders, then clicking on the order number to edit the order that needs to have the charge captured.

 it seems to me to be correct to use 'on-hold' after reservation.

I agree that this is not ideal at all, and would have much preferred to drop 'on-hold' and to have the capture being done either automatically on "Complete" or manually in "Processing", not least because it seems to be the only good way to implement partial capture as a future feature; and as you say, 'on-hold' seems to have a connotation of there being a problem with the order.  Also, several merchants disable the customer emails for this status.

If I was to implement this non-portably, I would probably have used a custom status, but based on the sources quoted above, it seems 'on-hold' is the only portable alternative matching the available documentation.

There are some other issues in going to "Processing", for instance, this is an end-state of "payment_complete()", and payment isn't complete. Also of course, if capture is done only when going to "Complete", then the order will (or could) have shipped already, and that's not a good time for capture to fail. 

Otherwise I would have added a filter for Vipps payment end state already; but it seems to me that I have to capture before going to 'processing' based on the docs.

I'm open to suggestions for handling this more smoothly, either as an optional opt-in mode or through a set of filters; but these are the issues.  Possibly I could as a selectable mode drop auto-capture on "Processing", use this as the end state for the Vipps process, and add a warning for orders that haven't been captured yet - and then merchants willing to take the small risk of the failure of capture between "Processing" and "Complete" would be able to use this workflow instead of the one involving "on-hold".

**Comment by thoaud** [comment]
I would at least make a option to capture immediately. I can see if I have some bright idea to the rest.

**Comment by cloveras** [comment]
Hi, @thoaud 

For "direct capture", Vipps needs to do additional checks due to compliance - please see https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-api-faq.md#what-is-the-difference-between-reserve-capture-and-direct-capture-and-how-do-i-change-payment-type

Christian, Vipps

**Comment by iverok** [comment]
And if  direct capture (virtual+downloadable, other products that are delivered at the same time as the purchase) is allowed, you can in fact modify the standard behaviour with filters for these products and go directly to processing/captured.

I see "no capture on processing" as a separate issue really.  The benefits are clear, the issues are that capture could then fail on the transition to "complete", which could be after shipping; and that all available documentation and the 'payment_complete' flow assumes payment is complete on "processing".   With explicit opt-in and sufficiently visible payment status display I guess that could be ok though. 

As a side note, we have in fact had one report from a customer where reserve was ok but capture failed. So it happens, even if rarely so.

**Comment by thoaud** [comment]
> For "direct capture", Vipps needs to do additional checks due to compliance
Yeah, it's not compliant with Norwegian laws.

The question in my head is, what could cause a reserved payment to not be captured?
> The money is reserved, but it has still not been transferred to the merchant, and in fact this transfer - the capture - can theoretically fail.
Of course this could fail if the order is too old, but that can be solved by having a meta field on the order holding the time of expiry for the reservation, and then using cron to put the order to 'on-hold' when the expiry time is met.

**Comment by iverok** [comment]
> The question in my head is, what could cause a reserved payment to not be captured?

In this case, it was well within the reservation period, but permanent. No idea what caused it.   You could also have temporary errors due to network issues and so forth.  I think reservation timeouts are less important as you have some control over that.

This risk could I feel be managable for users if they will remember to capture the order before shipping. For merchants manually doing fulfilment, this should be ok if the status is visible enough. For merchants that automate the flow; they would have to automate the capture before shipping too. But in an opt-in situation at least this would be ok I think. And of course then the change in behaviour re payment complete and the would be documented; not that much different than using custom order statuses. 

Of course I'd also like to avoid having too many modes and options as well, at least while the plugin is young - it would double the neccessary tests and make debugging more complex.  Also, interaction with other plugins and custom code assuming that "processing" means that payment is complete would be tricky to debug, as the users wouldn't neccessary know about those.

Anyway, this is why things are the way they are for now; and also why there is no partial capture, even though the button is there and ready for it.

**Comment by iverok** [comment]
This is now selectable as a setting in the options page with an explanation of what the risks are and why it isn't the default.
