### ISSUE TITLE
Vipps doesnt capture all shipping methods in Ingrid 

### ISSUE THREAD

**Issue by toronnet** [vippsas/vipps-woocommerce#81]
Our store has two shipping methods (pickup and home delivery), but only the method at the top of the list in Ingrid is visible in Vipps (see screenshots). We use both Klarna and Vipps in our store, and we're not having the same issue with Klarna. 

To see the issue:
Add a product to cart and move to checkout. As you can see Klarna finds two shipping methods and Vipps only finds one of them. 

Site url: https://helsekost.no/

Thanks.

![IMG_2371](https://user-images.githubusercontent.com/104771433/183369108-a131c760-19fa-4f9d-bf53-6c14a26c7bea.PNG)
![vipps1](https://user-images.githubusercontent.com/104771433/183369127-b63be30d-e416-4bea-a8d3-5fceee576b3f.png)
![vipps2](https://user-images.githubusercontent.com/104771433/183369141-8b1863d2-ca38-468b-ab2e-94198e6d80e5.png)

**Comment by iverok** [comment]
I see you are using Express Checkout but with a heavily modified cart/checkout page.  I assume you are not using the static shipping feature? 

Express Checkout handles shipping differently than the standard WooCommerce checkout mechanism (and Klarna is yet another matter) so it's not possible to guarantee that every shipping plugin will work for it. However in your case I would expect the methods to be correctly calculated; in particular since I got the second option when I tested (which is what I had chosen in the cart). 

I'm not sure about the extent of your modifications here, but you will probably need to debug what is generated by using a set of filters called in the shipping callback handler. 

Step one would be to hook into 'woo_vipps_shipping_callback_packages' and call WC()->shipping->calculate_shipping($packages); on the result. After this you should find all relevant (for the address) shipping methods in the value

   WC()->shipping->packages[0]['rates'];

You should also verify that you are not using any other filters here that would restrict the number of methods available.

**Comment by toronnet** [comment]
Thanks for getting back to me!

Could you please screenshot me the progress if you managed to get the second option (Bring pakke til postkasse) in your testing? As we're unable to do that. 


> I see you are using Express Checkout but with a heavily modified cart/checkout page. I assume you are not using the static shipping feature?
> 
> Express Checkout handles shipping differently than the standard WooCommerce checkout mechanism (and Klarna is yet another matter) so it's not possible to guarantee that every shipping plugin will work for it. However in your case I would expect the methods to be correctly calculated; in particular since I got the second option when I tested (which is what I had chosen in the cart).
> 
> I'm not sure about the extent of your modifications here, but you will probably need to debug what is generated by using a set of filters called in the shipping callback handler.
> 
> Step one would be to hook into 'woo_vipps_shipping_callback_packages' and call WC()->shipping->calculate_shipping($packages); on the result. After this you should find all relevant (for the address) shipping methods in the value
> 
> WC()->shipping->packages[0]['rates'];
> 
> You should also verify that you are not using any other filters here that would restrict the number of methods available.

**Comment by iverok** [comment]
I didn't; it's just that that's the one in your screenshot.  When retesting, I actually only get the pickup one. 

Also when testing, I just got my previous cart instead of the "real" cart I was trying to test with; I'm not sure if there is a caching issue there. But in any case, this should not affect the shipping calculation.

I note that one of your options has shipping metadata (pickup location). This is not possible to support in Express Checkout, as this does not allow for metadata.

**Comment by iverok** [comment]
jfr https://wordpress.org/support/topic/alle-fraktmetoder-dukker-ikke-opp-i-vipps/

**Comment by iverok** [comment]
Hi,

Could you add some testing to the filters I indicated? It's likely that Pickup Point  is not going to work without a lot of modifications here, but Pakke til Postkasse ought not be a problem. 

You should be able to use the normal Woo checkout process too of course, that will work with all shipping methods, but will require either that the user adds personal information by hand, or that this is fetched  using Vipps Login.
